### ISSUE TITLE
Unable to select signature position

### ISSUE THREAD

**Issue by vikasrawal** [strukturag/nextcloud-certificate24#363] opened 2024-05-10 14:21 UTC
I am unable to select signature position in certificate24 app in nextcloud (AIO). When I click on select signature position, the file does not open. A dialog box in the background  shows a circular animated ring for waiting keeps showing. 

Is this a known problem? Would appreciate any guidance.

**Comment by fancycode** [comment] 2024-05-13 06:49
Does this happen with all files or only with some of them?

Please check your browser console logs for any errors. Also check your nextcloud.log if an error is logged there.

**Comment by Pjort** [comment] 2024-07-05 11:47
I got the same issue.

I get the following error in the console log:

Uncaught TypeError: Promise.withResolvers is not a function
    at getPdfManager (pdf.worker-4.1.392.mjs:56883:44)
    at setupDoc (pdf.worker-4.1.392.mjs:57021:7)
    at pdf.worker-4.1.392.mjs:57365:7
    at MessageHandler._onComObjOnMessage (pdf.worker-4.1.392.mjs:56352:7)
getPdfManager @ pdf.worker-4.1.392.mjs:56883
setupDoc @ pdf.worker-4.1.392.mjs:57021
(anonymous) @ pdf.worker-4.1.392.mjs:57365
MessageHandler._onComObjOnMessage @ pdf.worker-4.1.392.mjs:56352

**Comment by Pjort** [comment] 2024-07-06 05:50
From the looks of things the PDF selector is dynamically loaded using the externalComponent service.

src/services/externalComponent.js

Which in turn uses some vinegarApi that then pulls from a server?

I haven't had the time to pull the code and make a test environment. But I assume the problem is located where ever the vinegarApi is pulling data from?

**Comment by fancycode** [comment] 2024-07-08 06:12
> I got the same issue.
> 
> I get the following error in the console log:
> 
> ```
> Uncaught TypeError: Promise.withResolvers is not a function
> at getPdfManager (pdf.worker-4.1.392.mjs:56883:44)
> at setupDoc (pdf.worker-4.1.392.mjs:57021:7)
> at pdf.worker-4.1.392.mjs:57365:7
> at MessageHandler._onComObjOnMessage (pdf.worker-4.1.392.mjs:56352:7)
> getPdfManager @ pdf.worker-4.1.392.mjs:56883
> setupDoc @ pdf.worker-4.1.392.mjs:57021
> (anonymous) @ pdf.worker-4.1.392.mjs:57365
> MessageHandler._onComObjOnMessage @ pdf.worker-4.1.392.mjs:56352

Hi @Pjort which browser / OS are you running this in? `Promise.withResolvers` should be available according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers

We are using https://mozilla.github.io/pdf.js/ for rendering the documents in the browser and this is where the error is triggered.

**Comment by Pjort** [comment] 2024-07-08 06:37
Funny, I tried on 2 different nextcloud servers and 3 different devices. But I actually used the same Browser on all three devices. I am using the Thorium browser, and cromium based.

Now when I tried with a firefox Browser it works :)

Maybe a error modal should pop up to use a different browser when pdf.js isn't avaible.

**Comment by fancycode** [comment] 2024-07-08 06:42
Hmm, I will have to check if we can detect errors like this. pdf.js itself could be loaded (we already check this) but then failed to execute some code internally later.

But we could add a polyfill for `Promise.withResolvers` in any case. Thanks for checking.

**Comment by fancycode** [comment] 2024-07-22 15:03
Closing in favor of #400

**Closed by fancycode** 2024-07-22 15:03 UTC
